-- 코드를 입력하세요
SELECT CASE WHEN SUBSTR(TO_CHAR(DATETIME,'HH24'),1,1)=0 THEN SUBSTR(TO_CHAR(DATETIME,'HH24'),2,1)
ELSE SUBSTR(TO_CHAR(DATETIME,'HH24'),1,2)
END AS HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME,'HH24')>=09 AND TO_CHAR(DATETIME, 'HH24')<=19
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY (CASE WHEN LENGTH(HOUR)=1 THEN 1 ELSE 2 END), HOUR;